### PR TITLE
add $ in composer require command

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by GeeH** [comment]
That's even worse than my PR. I salute you.

**Comment by GeeH** [comment]
I wouldn't merge this personally - I'd prefer to have the console in the fenced codeblocks. It's a pita for copy pasta when there's a $ in the line

**Comment by Ocramius** [comment]
I like money, but my console command fails if I paste in the $ :-P

**Comment by Ocramius** [comment]
Deferring decision to @malukenho

**Comment by samsonasik** [comment]
it's for consistencies, just like in contributing.md https://github.com/Roave/StrictPhp/blob/master/CONTRIBUTING.md

**Comment by Ocramius** [comment]
Actually a good point. Still, ball to @malukenho :-)

**Comment by danizord** [comment]
:+1: 

I like the leading `$` and `#`, they tell if you should or not run the command with `sudo`.

**Comment by malukenho** [comment]
Merged as the most of computers has a mouse to select what you want to copy, and also has ways to delete chars if you need.

**Comment by malukenho** [comment]
Thanks @samsonasik  :beers:

**Pull request merged**
